### ISSUE TITLE
Results/formatting issue when querying db

### ISSUE THREAD

**Issue by jmgnc** [idaholab/STIG#2]
See attached screenshot.  I attempted the query database that you see in the screen shot `select from malware`, and then the 0-3 options appeared at the bottom and now I have to scroll the window.  I don't think that this is correct.  This is with commit d6d09401ea9988d8a92caed9427ee562bd24d5b7.
<img width="1260" alt="Screen Shot 2019-05-15 at 5 35 06 PM" src="https://user-images.githubusercontent.com/11578757/57818278-107cd080-7738-11e9-8048-e2e302238798.png">

**Comment by jthaile** [comment]
I haven't been able to reproduce this yet, it looks like an issue with the jquery widget.  That commit updated jquery, did you run yarn install after pulling?  If it persists, rm node_modules and rerun yarn install.

**Comment by jmgnc** [comment]
Yeah, I did some other work, and it hasn't happened again.  Also, this was from a clean tree on Wednesday, but it could have been issues w/ an old yarn used to pull in deps first.

**Comment by jthaile** [comment]
OK, I'll keep this open for a while in case this issue appears again.
