### ISSUE TITLE
yarn make throwing Error: Cannot find module './util/terminate'

### ISSUE THREAD

**Issue by bodacea** [idaholab/STIG#21]
Hi - following mac install instructions, getting to "yarn make" and getting error "Error: Cannot find module './util/terminate'".    Not sure if this is related to "brew install yarn --without-node" not being available any more. 

Also readme says "Download and extract the stig.tar archive" - am assuming this is superceded by "download the github repo"?

**Comment by jthaile** [comment]
I haven't been able to reproduce this. I think there could be an issue with building a packaged binary that I need to investigate further.

To install yarn on a mac follow the instructions at https://yarnpkg.com/en/docs/install#mac-rc
Once yarn is installed try the following command which will run stig in developer mode:
`yarn start`

If that fails, please copy the error message and post it here.

**Comment by bodacea** [comment]
Installing yarn from https://yarnpkg.com/en/docs/install#mac-rc and doing a clean reinstall of everything else solved the problem, thank you!
