### ISSUE TITLE
Delete node from orientdb when delete operation is performed within STIG

### ISSUE THREAD

**Issue by Fhree99** [idaholab/STIG#50]
Currently the right click delete function within STIG does not delete the node form the database. This can be seen when querying the database after restarting the application or clearing the graph. Adding this feature would be helpful as the current workaround is downloading the json bundle, creating a new db, and then committing the objects in the updated json bundle to the new db.

**Comment by zakaray24** [comment]
Add in dropdown Graph select to --> `delete selected from db`
