### ISSUE TITLE
SCOs are not committing to OrientDB

### ISSUE THREAD

**Issue by z-priest** [idaholab/STIG#55]
New STIX Cyber Observable's are not saving to the database.

Missing created/modified dates.

**Comment by zakaray24** [comment]
![image](https://user-images.githubusercontent.com/19195413/121599810-d490c400-ca00-11eb-941d-873d4fa00f04.png)

**Comment by zakaray24** [comment]
SCOs don't require created/modified.  STIG app does.  update db/schema.ts, all SCOs to not extend core.

Example:
![image](https://user-images.githubusercontent.com/19195413/121708175-89c08c00-ca94-11eb-8170-007f621d91b4.png)

**Comment by zakaray24** [comment]
https://docs.oasis-open.org/cti/stix/v2.1/csprd01/stix-v2.1-csprd01.html#_Toc16070681

**Comment by zakaray24** [comment]
Commit-all from dropdown needs another look.  Relationships aren't committing because they are missing spec_version even though it's present in the json_editor.

Works if you simply look at each relationship via click before pushing commit all

**Comment by zakaray24** [comment]
Related,
If spec_version exists on a bundle, all nodes/rels need to inherit this to adhere to db schema.
